### ISSUE TITLE
Removed from Firefox for using an outdated SDK

### ISSUE THREAD

**Issue by gumadozucia** [lostdj/FxExtPasteNGoHtk#8]
The extensions has been removed from my browser and this page appeared after clicking learn more: https://blocked.cdn.mozilla.net/i1423.html

**Comment by lostdj** [comment]
Sorry, don't want to touch this FF addon development madness.

I've just tried this extension and it works just fine, while also having a lot of configurable options: https://addons.mozilla.org/en-US/firefox/addon/paste-and-go-3-again/
You may need to restart FF after ticking "Assign high priority to Hotkeys".
